name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: Breaking Changes 🛠
      label: 'breaking-change'
    - title: Exciting New Features 🎉
      labels: 'feature'
    - title: Bug Fixing 🙇
      labels: 'fix'
    - title: CI Changes 🤖
      labels: 'ci'
    - title: Miscellaneous 🧺
      labels: '*'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
#version-resolver:
#    major:
#        labels:
#            - 'major'
#    minor:
#        labels:
#            - 'minor'
#    patch:
#        labels:
#            - 'patch'
#    default: patch
template: |
    ## Changes

    $CHANGES
autolabeler:
    - label: 'chore'
      title:
          - '/chore/i'
      branch:
          - '/chore\/.+/'
    - label: 'fix'
      title:
          - '/fix/i'
      branch:
          - '/fix\/.+/'
    - label: 'feature'
      title:
          - '/feat/i'
      branch:
          - '/feature\/.+/'
    - label: 'ci'
      title:
          - '/ci/i'
    - label: 'refactor'
      title:
          - '/refactor/i'
      branch:
          - '/refactor\/.+/'
