name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: Breaking Changes 🛠
      label: 'breaking-change'
    - title: Exciting New Features 🎉
      label: 'feature'
    - title: Bug Fixing 🙇
      label: 'fix'
    - title: CI Changes 🤖
      label: 'ci'
    - title: Miscellaneous 🧺
      labels:
        - 'chore'
        - 'documentation'
        - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER) $BODY'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
template: |
    ## Changes

    $CHANGES
autolabeler:
    - label: 'chore'
      branch:
          - '/^chore[^/]*\/.+/'
    - label: 'fix'
      branch:
          - '/^fix[^/]*\/.+/'
    - label: 'feature'
      branch:
          - '/^feat[^/]*\/.+/'
    - label: 'ci'
    - label: 'refactor'
      branch:
          - '/^refactor[^/]*\/.+/'
    - label: 'documenation'
      branch:
        - '/^doc[^/]*\/.+/'
